The following Notebook has been used for step by step debugging

In [1]:
import src.unconstrained_min as um
import src.utils as utils
import tests.examples as examples
import numpy as np

1. TEST THE EXAMPLES 

In [2]:
x = np.array([1.0, 2.0])

#test quad_circle
f, grad, hess = examples.quad_circle(x, need_hessian=True)
print("Function value:", f)
print("Gradient:", grad)
print("Hessian:\n", hess)



Function value: 5.0
Gradient: [2. 4.]
Hessian:
 [[2. 0.]
 [0. 2.]]


In [3]:
#test quad_elipse
print("Quad ellipse with x = [1.0, 2.0]")  
f, grad, hess = examples.quad_ellipse(x, need_hessian=True)
print("Function value:", f)
print("Gradient:", grad)
print("Hessian:\n", hess)

#test quad_rotated_ellipse
print("Quad rotated ellipse with x = [1.0, 2.0]")
f, grad, hess = examples.quad_rotated_ellipse(x, need_hessian=True)
print("Function value:", f)
print("Gradient:", grad)
print("Hessian:\n", hess)

#test rosenbrock
print("Rosenbrock with x = [1.0, 2.0]")
f, grad, hess = examples.rosenbrock(x, need_hessian=True)
print("Function value:", f)
print("Gradient:", grad)
print("Hessian:\n", hess)

#test linear 
print("Linear with x = [1.0, 2.0]")
f, grad, hess = examples.linear(x, need_hessian=False)
print("Function value:", f)
print("Gradient:", grad)
print("Hessian:\n", hess)

#test smooth_triangle
print("Smooth triangle with x = [1.0, 2.0]")
f, grad, hess = examples.smooth_triangle(x, need_hessian=True)
print("Function value:", f)
print("Gradient:", grad)
print("Hessian:\n", hess)




Quad ellipse with x = [1.0, 2.0]
Function value: 401.0
Gradient: [  2. 400.]
Hessian:
 [[  2   0]
 [  0 200]]
Quad rotated ellipse with x = [1.0, 2.0]
Function value: 6.776970050681143
Gradient: [-20.97302995  17.26348503]
Hessian:
 [[150.5        -85.73651497]
 [-85.73651497  51.5       ]]
Rosenbrock with x = [1.0, 2.0]
Function value: 100.0
Gradient: [-400.  200.]
Hessian:
 [[ 402. -400.]
 [-400.  200.]]
Linear with x = [1.0, 2.0]
Function value: 247.0
Gradient: [  1. 123.]
Hessian:
 None
Smooth triangle with x = [1.0, 2.0]
Function value: 992.6136834352898
Gradient: [ 991.94794127 2976.80585658]
Hessian:
 [[ 992.61368344 2976.80585658]
 [2976.80585658 8930.52731116]]


2.TEST THE MINIMIZATION

In [4]:
from tests.examples import quad_circle, quad_ellipse, quad_rotated_ellipse, rosenbrock, linear, smooth_triangle

In [6]:
functions = [
    ("Quad Circle", quad_circle, [1.0, 1.0]),
    ("Quad Ellipse", quad_ellipse, [1.0, 1.0]),
    ("Quad Rotated Ellipse", quad_rotated_ellipse, [1.0, 1.0]),
    ("Rosenbrock", rosenbrock, [-1.0, 2.0]),
    ("Linear", linear, [1.0, 1.0]),
    ("Smooth Triangle", smooth_triangle, [1.0, 1.0])
]

results = []
for name, func, x0 in functions[3:]:
    max_iter = 10000 if name == "Rosenbrock" else 100
    print(f"\n🔍 Testing Gradient Descent on: {name} with x0 = {x0}")
    x_final, f_final, success, x_path, f_path = um.minimize(f=func, x0=x0, method='GD',
                                                                 obj_tol=1e-12, param_tol=1e-8, max_iter=max_iter)
    print(f"Final x: {x_final}")
    print(f"Final function value: {f_final}")
    print(f"Success: {success}")
    print(f"Iterations: {len(x_path)-1}")
    results.append((name, x_final, f_final, success, len(x_path)-1))
                                                             



🔍 Testing Gradient Descent on: Rosenbrock with x0 = [-1.0, 2.0]
Iter 1: x = [-1.38671875  1.8046875 ], f(x) = 7.095948317088187
Iter 7751: x = [0.99989437 0.99978771], f(x) = 1.1267173493005898e-08
Final x: [0.99989437 0.99978771]
Final function value: 1.1267173493005898e-08
Success: True
Iterations: 7750

🔍 Testing Gradient Descent on: Linear with x0 = [1.0, 1.0]
Iter 1: x = [   0. -122.], f(x) = -15006.0
Final x: [   -99. -12299.]
Final function value: -1512876.0
Success: False
Iterations: 100

🔍 Testing Gradient Descent on: Smooth Triangle with x0 = [1.0, 1.0]
Iter 1: x = [ 0.61568723 -0.15499983], f(x) = 4.207136986647966
Iter 29: x = [-3.46572886e-01 -9.76799665e-07], f(x) = 2.559266696664345
Final x: [-3.46572886e-01 -9.76799665e-07]
Final function value: 2.559266696664345
Success: True
Iterations: 28


In [8]:
functions = [
    ("Quad Circle", quad_circle, [1.0, 1.0]),
    ("Quad Ellipse", quad_ellipse, [1.0, 1.0]),
    ("Quad Rotated Ellipse", quad_rotated_ellipse, [1.0, 1.0]),
    ("Rosenbrock", rosenbrock, [-1.0, 2.0]),
    #("Linear", linear, [1.0, 1.0]),
    ("Smooth Triangle", smooth_triangle, [1.0, 1.0])
]
results = []
for name, func, x0 in functions[3:]:
    print(f"\n🔍 Testing Gradient Descent on: {name} with x0 = {x0}")
    x_final, f_final, success, x_path, f_path = um.minimize(f=func, x0=x0, method='NT',
                                                                 obj_tol=1e-12, param_tol=1e-8, max_iter=100)
    print(f"Final x: {x_final}")
    print(f"Final function value: {f_final}")
    print(f"Success: {success}")
    print(f"Iterations: {len(x_path)-1}")
    results.append((name, x_final, f_final, success, len(x_path)-1))


🔍 Testing Gradient Descent on: Rosenbrock with x0 = [-1.0, 2.0]
Iter 1: x = [-1.01005025  1.0201005 ], f(x) = 4.040303032827961
Iter 21: x = [1. 1.], f(x) = 5.4357446750385345e-30
Final x: [1. 1.]
Final function value: 5.4357446750385345e-30
Success: True
Iterations: 20

🔍 Testing Gradient Descent on: Smooth Triangle with x0 = [1.0, 1.0]
Iter 1: x = [0.81041242 0.73119842], f(x) = 18.87640039338445
Iter 9: x = [-3.46573590e-01 -7.26375117e-18], f(x) = 2.5592666966582156
Final x: [-3.46573590e-01 -7.26375117e-18]
Final function value: 2.5592666966582156
Success: True
Iterations: 8
