The following Notebook has been used for step by step debugging

In [6]:
import src.unconstrained_min as um
import src.utils as utils
import tests.examples as examples
import numpy as np

1. TEST THE EXAMPLES 

In [7]:
x = np.array([1.0, 2.0])

#test quad_circle
f, grad, hess = examples.quad_circle(x, need_hessian=True)
print("Function value:", f)
print("Gradient:", grad)
print("Hessian:\n", hess)



Function value: 5.0
Gradient: [2. 4.]
Hessian:
 [[2. 0.]
 [0. 2.]]


In [10]:
#test quad_elipse
print("Quad ellipse with x = [1.0, 2.0]")  
f, grad, hess = examples.quad_ellipse(x, need_hessian=True)
print("Function value:", f)
print("Gradient:", grad)
print("Hessian:\n", hess)

#test quad_rotated_ellipse
print("Quad rotated ellipse with x = [1.0, 2.0]")
f, grad, hess = examples.quad_rotated_ellipse(x, need_hessian=True)
print("Function value:", f)
print("Gradient:", grad)
print("Hessian:\n", hess)

#test rosenbrock
print("Rosenbrock with x = [1.0, 2.0]")
f, grad, hess = examples.rosenbrock(x, need_hessian=True)
print("Function value:", f)
print("Gradient:", grad)
print("Hessian:\n", hess)

#test linear 
print("Linear with x = [1.0, 2.0]")
f, grad, hess = examples.linear(x, need_hessian=False)
print("Function value:", f)
print("Gradient:", grad)
print("Hessian:\n", hess)

#test smooth_triangle
print("Smooth triangle with x = [1.0, 2.0]")
f, grad, hess = examples.smooth_triangle(x, need_hessian=True)
print("Function value:", f)
print("Gradient:", grad)
print("Hessian:\n", hess)




Quad ellipse with x = [1.0, 2.0]
Function value: 401.0
Gradient: [  2. 400.]
Hessian:
 [[  2   0]
 [  0 200]]
Quad rotated ellipse with x = [1.0, 2.0]
Function value: 6.776970050681143
Gradient: [-20.97302995  17.26348503]
Hessian:
 [[150.5        -85.73651497]
 [-85.73651497  51.5       ]]
Rosenbrock with x = [1.0, 2.0]
Function value: 100.0
Gradient: [-400.  200.]
Hessian:
 [[ 402. -400.]
 [-400.  200.]]
Linear with x = [1.0, 2.0]
Function value: 247.0
Gradient: [  1. 123.]
Hessian:
 None
Smooth triangle with x = [1.0, 2.0]
Function value: 992.6136834352898
Gradient: [ 991.94794127 2976.80585658]
Hessian:
 [[ 992.61368344 2976.80585658]
 [2976.80585658 8930.52731116]]


2.TEST THE MINIMIZATION

In [ ]:
from tests.examples import quad_circle, quad_ellipse, quad_rotated_ellipse, rosenbrock, linear, smooth_triangle

In [11]:
functions = [
    ("Quad Circle", quad_circle, [1.0, 1.0]),
    ("Quad Ellipse", quad_ellipse, [1.0, 1.0]),
    ("Quad Rotated Ellipse", quad_rotated_ellipse, [1.0, 1.0]),
    ("Rosenbrock", rosenbrock, [-1.0, 2.0]),
    ("Linear", linear, [1.0, 1.0]),
    ("Smooth Triangle", smooth_triangle, [1.0, 1.0])
]

results = []
for name, func, x0 in functions:
    max_iter = 10000 if name == "Rosenbrock" else 100
    print(f"\n🔍 Testing Gradient Descent on: {name} with x0 = {x0}")


NameError: name 'quad_ellipse' is not defined